services:
  - type: web
    name: 1791technology-rest-api
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: API_VERSION
        value: v1
      - key: API_PREFIX
        value: /api
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100
      - key: LOG_LEVEL
        value: info
      - key: LOG_FILE
        value: logs/app.log
      - key: BCRYPT_SALT_ROUNDS
        value: 12
      - key: SWAGGER_ENABLED
        value: true
      - key: JWT_EXPIRES_IN
        value: 15m
      - key: JWT_REFRESH_EXPIRES_IN
        value: 7d
      # These will need to be set manually in Render dashboard for security:
      # - MONGODB_URI (your MongoDB connection string)
      # - JWT_SECRET (strong secret key)
      # - JWT_REFRESH_SECRET (strong refresh secret)
      # - CORS_ORIGIN (your frontend URL after Vercel deployment)
